### ISSUE TITLE
Saving values not working as expected

### ISSUE THREAD

**Issue by ithinkido** [grblHAL/Plugin_WebUI#5]
I am trying to save values for max travel from the webUI , but I think there may be an issue with the backend for saving these values. 
As an emaple , trying to save the values for max travel for x and y as x = 420 and y = 290 

![image](https://user-images.githubusercontent.com/52834821/194390087-9207d634-8de5-475f-afdd-ef489351b5bd.png)
( these values were saved using the save button) 
![image](https://user-images.githubusercontent.com/52834821/194390324-f942d7a4-4f45-435a-a03f-9e6250b34446.png)

Upon restart, the values are not as expected
 This is after restart
 
![image](https://user-images.githubusercontent.com/52834821/194390536-e1ae048a-b525-4d19-a972-6cc04474f9d2.png)

**Comment by terjeio** [comment]
This is a bug - will fix in the next commit. Thanks for reporting.

**Comment by ithinkido** [comment]
Tested and working perfect now. Thanks for the fix
