### ISSUE TITLE
Network names with a space are not being saved correctly

### ISSUE THREAD

**Issue by ithinkido** [grblHAL/Plugin_WebUI#6]
**Describe the bug**
Saving network names which include a space is not working when using webUI for grblHAL

**To Reproduce**

1. Select network mode - Access Point / Station
2. Select a network name which includes a space
3. Save changes
4. Reset board
5. Go back to setting page and check if name was correctly saved

**Expected behavior**
The name in this case is  "FRITZ!box 7530". 

**Screenshots**

![image](https://user-images.githubusercontent.com/52834821/194348599-585a7091-181e-4c04-aba7-f114333d450d.png)

**ESP3D Firmware**
- Version:3.0
- Web UI Version: https://github.com/luc-github/ESP3D-WEBUI/tree/3.0/dist/CNC/GRBLHal
- Wifi mode:[e.g. STA]
- No changes done to FW 

**Target Firmware**
 - Name: grblHAL
 - Version  : Lastest version pulled from here today - https://github.com/grblHAL/ESP32

**Board used**
 - MCU: ESP32
 - Flash size:  4M: 2M/2M

**Browser used**
- Name: Firefox
- Version  105.0.1 (64-bit)
- Operating system Windows 10

**Additional context**
When exporting the json config file it seems as though the name is correctly listed
```   
{
    "id": "74",
    "label": "WiFi Station (STA) SSID",
    "value": "FRITZ!Box 7530"
   },
```

Looking at the reply for `[ESP400]` it seems like grblHAL may not be saving the name correctly. 

```
[ESP400]
.....
.....
....
{
   "F": "WiFi/WiFi",
   "P": "74",
   "T": "S",
   "V": "FRITZ!Box\\",
   "H": "WiFi Station (STA) SSID",
   "S": "64"
  },
....
....
````

**Comment by terjeio** [comment]
Oops - I was not aware that the WebUI is escaping space characters. Will fix in the next commit.

**Comment by luc-github** [comment]
@terjeio the doc was not well formated to markdown so information was not really visible - sorry 
I have just added the 3 spaces to make LF in conventions:
https://github.com/luc-github/ESP3D-WEBUI/blob/3.0/Memo/Commands.md

**Comment by terjeio** [comment]
@ithinkido Spaces is hostnames are not allowed according to RFC1123, I may add validation later. mDNS discovery breaks if present.
@luc-github options for enabling mDNS and SSDP is on the way up now.

**Comment by ithinkido** [comment]
The new fix allows me to use the network name with the space. Thanks
