### ISSUE TITLE
Cant connect to WebUI

### ISSUE THREAD

**Issue by drom89** [grblHAL/Plugin_WebUI#9]
So i build fw on web builder, flash it to ESP32.
Im using ESP32 as AccesPoint.
Tried to connect thru web browser but i get error: This site can’t be reached192.168.5.1 refused to connect.
I can ping the IP addres no problem.

Any suggestions ? 

```
[VER:1.1f.20230129:]
[OPT:VNSL,35,1024,3,0]
[AXS:3:XYZ]
[NEWOPT:ENUMS,RT+,REBOOT,TC,SED,RTC,WIFI,SD]
[FIRMWARE:grblHAL]
[NVS STORAGE:*FLASH]
[DRIVER:ESP32]
[DRIVER VERSION:230125]
[DRIVER OPTIONS:4.3.1]
[BOARD:ESPDUINO-32 Wemos D1 R32]
[WIFI MAC:EC:62:60:A2:0C:D8]
[IP:192.168.5.1]
[PLUGIN:WebUI v0.14]
[PLUGIN:SDCARD v1.07]
```

**Comment by terjeio** [comment]
Are HTTP and WebSocket services enabled ($70=3) and WebSocket port set to 81 ($307=81)?

**Comment by drom89** [comment]
Ok, after few more flashes, it start to work...
